version: '3'
services:
  master:
    container_name: master
    build: .
    environment:
      FLASK_APP: master_app.py
      NODE: master
      PORT: 8820
    ports:
      - "8820:8820"
    volumes:
      - .:/code
    stdin_open: true
    tty: true
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
  dfs_celery:
    container_name: dfs_celery
    build:
      context: .
      dockerfile: Dockerfile_dfs_celery
    volumes:
      - .:/code
      - ./storage_sn0_5000:/storage_sn0_5000
      - ./storage_sn1_5050:/storage_sn1_5050
      - ./storage_sn2_6000:/storage_sn2_6000
      - ./storage_sn3_6050:/storage_sn3_6050
      - ./storage_sn4_7000:/storage_sn4_7000
    stdin_open: true
    tty: true
  sn0:
    container_name: sn0
    build: .
    environment:
      FLASK_APP: storage_node_app.py
      NODE: sn0
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    stdin_open: true
    tty: true
  sn1:
    container_name: sn1
    build: .
    environment:
      FLASK_APP: storage_node_app.py
      NODE: sn1
      PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - .:/code
    stdin_open: true
    tty: true
  sn2:
    container_name: sn2
    build: .
    environment:
      FLASK_APP: storage_node_app.py
      NODE: sn2
      PORT: 6000
    ports:
      - "6000:6000"
    volumes:
      - .:/code
    stdin_open: true
    tty: true
  sn3:
    container_name: sn3
    build: .
    environment:
      FLASK_APP: storage_node_app.py
      NODE: sn3
      PORT: 6050
    ports:
      - "6050:6050"
    volumes:
      - .:/code
    stdin_open: true
    tty: true
  sn4:
    container_name: sn4
    build: .
    environment:
      FLASK_APP: storage_node_app.py
      NODE: sn4
      PORT: 7000
    ports:
      - "7000:7000"
    volumes:
      - .:/code
    stdin_open: true
    tty: true